name: Deployment to production
on:
    push:
        branches: [ prod ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          -
            name: checkout code
            uses: actions/checkout@v2
          -
            name: Docker login
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: techindustry/elevateoff:${{ github.sha }}
              build-args: |
                DATABASE_URL=${{ secrets.DATABASE_URL }}
                NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          -
            name: Deploy to the vps
            uses: appleboy/ssh-action@v1.2.1
            with:
              host: ${{ secrets.HOST }}
              username: root
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                docker pull techindustry/elevateoff:${{ github.sha }}
                docker stop elevateoff
                docker run --name elevateoff -d -p 3000:3000 techindustry/elevateoff:${{ github.sha }}
